// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Core__Error from "../src/Core__Error.mjs";
import * as RescriptCore from "../src/RescriptCore.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function panicTest() {
  var caught;
  try {
    caught = RescriptCore.panic("uh oh");
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === Core__Error.$$Error) {
      caught = err._1.message;
    } else {
      throw err;
    }
  }
  Test.run([
        [
          "ErrorTests.res",
          8,
          22,
          43
        ],
        "Should resolve test"
      ], caught, (function (prim0, prim1) {
          return prim0 === prim1;
        }), "Panic! uh oh");
}

panicTest();

export {
  panicTest ,
}
/*  Not a pure module */
